// Generated by ts-to-zod
import { z } from "zod";

export const jsonRecordSchema = z.record(z.string(), z.unknown());

export const nullableJsonRecordSchema = jsonRecordSchema.nullable();

export const dateInputSchema = z.union([z.string(), z.number()]);

export const errorResultSchema = z.object({
    ok: z.literal(false),
    error: z.object({
        message: z.string()
    })
});

export const htmlResponseSchema = z.string();

export const groupOptionsSchema = z.object({
    id: z.string(),
    tier: z.string().optional()
});

export const groupConcurrencyConfigSchema = z.object({
    default: z.number(),
    tiers: z.record(z.string(), z.number()).optional()
});

export const queueOptionsSchema = z.object({
    expireInSeconds: z.number().optional(),
    retentionSeconds: z.number().optional(),
    deleteAfterSeconds: z.number().optional(),
    retryLimit: z.number().optional(),
    retryDelay: z.number().optional(),
    retryBackoff: z.boolean().optional(),
    retryDelayMax: z.number().optional()
});

export const connectionOptionsSchema = z.object({
    db: z.unknown().optional()
});

export const jobOptionsSchema = z.object({
    id: z.string().optional(),
    priority: z.number().optional(),
    startAfter: dateInputSchema.optional(),
    singletonKey: z.string().optional(),
    singletonSeconds: z.number().optional(),
    singletonNextSlot: z.boolean().optional(),
    keepUntil: dateInputSchema.optional(),
    group: groupOptionsSchema.optional(),
    deadLetter: z.string().optional()
});

export const sendOptionsSchema = jobOptionsSchema.and(queueOptionsSchema).and(connectionOptionsSchema);

export const scheduleOptionsSchema = sendOptionsSchema.and(z.object({
    tz: z.string().optional(),
    key: z.string().optional()
}));

export const fetchOptionsSchema = z.object({
    includeMetadata: z.boolean().optional(),
    priority: z.boolean().optional(),
    orderByCreatedOn: z.boolean().optional(),
    batchSize: z.number().optional(),
    ignoreStartAfter: z.boolean().optional(),
    groupConcurrency: z.union([z.number(), groupConcurrencyConfigSchema]).optional(),
    ignoreGroups: z.array(z.string()).optional().nullable(),
    db: z.unknown().optional()
});

export const findJobsOptionsSchema = z.object({
    id: z.string().optional(),
    key: z.string().optional(),
    data: jsonRecordSchema.optional(),
    queued: z.boolean().optional(),
    db: z.unknown().optional()
});

export const insertOptionsSchema = z.object({
    returnId: z.boolean().optional(),
    db: z.unknown().optional()
});

export const updateQueueOptionsSchema = queueOptionsSchema.and(z.object({
    deadLetter: z.string().optional(),
    warningQueueSize: z.number().optional()
}));

export const queueResultSchema = queueOptionsSchema.and(z.object({
    name: z.string(),
    policy: z.string().optional(),
    partition: z.boolean().optional(),
    deadLetter: z.string().optional(),
    warningQueueSize: z.number().optional(),
    deferredCount: z.number(),
    queuedCount: z.number(),
    activeCount: z.number(),
    totalCount: z.number(),
    table: z.string(),
    createdOn: z.string(),
    updatedOn: z.string(),
    singletonsActive: z.array(z.string()).nullable()
}));

export const jobSchema = z.object({
    id: z.string(),
    name: z.string(),
    data: jsonRecordSchema,
    expireInSeconds: z.number(),
    signal: z.unknown(),
    groupId: z.string().optional().nullable(),
    groupTier: z.string().optional().nullable()
});

export const jobWithMetadataSchema = jobSchema.and(z.object({
    priority: z.number(),
    state: z.union([z.literal("created"), z.literal("retry"), z.literal("active"), z.literal("completed"), z.literal("cancelled"), z.literal("failed")]),
    retryLimit: z.number(),
    retryCount: z.number(),
    retryDelay: z.number(),
    retryBackoff: z.boolean(),
    retryDelayMax: z.number().optional(),
    startAfter: z.string(),
    startedOn: z.string(),
    singletonKey: z.string().nullable(),
    singletonOn: z.string().nullable(),
    deleteAfterSeconds: z.number(),
    createdOn: z.string(),
    completedOn: z.string().nullable(),
    keepUntil: z.string(),
    policy: z.string(),
    deadLetter: z.string(),
    output: jsonRecordSchema
}));

export const commandResponseSchema = z.object({
    jobs: z.array(z.string()),
    requested: z.number(),
    affected: z.number()
});

export const scheduleSchema = z.object({
    name: z.string(),
    key: z.string(),
    cron: z.string(),
    timezone: z.string(),
    data: jsonRecordSchema.optional(),
    options: sendOptionsSchema.optional()
});

export const bamStatusSummarySchema = z.object({
    status: z.union([z.literal("pending"), z.literal("in_progress"), z.literal("completed"), z.literal("failed")]),
    count: z.number(),
    lastCreatedOn: z.string()
});

export const metaResultSchema = z.object({
    states: z.record(z.string(), z.string()),
    policies: z.record(z.string(), z.string()),
    events: z.record(z.string(), z.string())
});

export const metaResponseSchema = z.object({
    ok: z.literal(true),
    result: metaResultSchema
});

export const sendRequestSchema = z.object({
    name: z.string(),
    data: nullableJsonRecordSchema.optional(),
    options: sendOptionsSchema.optional()
});

export const sendResponseSchema = z.object({
    ok: z.literal(true),
    result: z.string().nullable()
});

export const sendAfterRequestSchema = z.object({
    name: z.string(),
    data: nullableJsonRecordSchema.optional(),
    options: sendOptionsSchema.optional().nullable(),
    after: dateInputSchema
});

export const sendAfterResponseSchema = z.object({
    ok: z.literal(true),
    result: z.string().nullable()
});

export const sendThrottledRequestSchema = z.object({
    name: z.string(),
    data: nullableJsonRecordSchema.optional(),
    options: sendOptionsSchema.optional().nullable(),
    seconds: z.number(),
    key: z.string().optional()
});

export const sendThrottledResponseSchema = z.object({
    ok: z.literal(true),
    result: z.string().nullable()
});

export const sendDebouncedRequestSchema = z.object({
    name: z.string(),
    data: nullableJsonRecordSchema.optional(),
    options: sendOptionsSchema.optional().nullable(),
    seconds: z.number(),
    key: z.string().optional()
});

export const sendDebouncedResponseSchema = z.object({
    ok: z.literal(true),
    result: z.string().nullable()
});

export const jobInsertSchema = z.object({
    id: z.string().optional(),
    data: jsonRecordSchema.optional(),
    priority: z.number().optional(),
    retryLimit: z.number().optional(),
    retryDelay: z.number().optional(),
    retryBackoff: z.boolean().optional(),
    retryDelayMax: z.number().optional(),
    startAfter: dateInputSchema.optional(),
    singletonKey: z.string().optional(),
    singletonSeconds: z.number().optional(),
    expireInSeconds: z.number().optional(),
    deleteAfterSeconds: z.number().optional(),
    retentionSeconds: z.number().optional(),
    group: groupOptionsSchema.optional(),
    deadLetter: z.string().optional()
});

export const insertResponseSchema = z.object({
    ok: z.literal(true),
    result: z.array(z.string()).nullable()
});

export const fetchRequestSchema = z.object({
    name: z.string(),
    options: fetchOptionsSchema.optional()
});

export const fetchResponseSchema = z.object({
    ok: z.literal(true),
    result: z.union([z.array(jobWithMetadataSchema), z.array(jobSchema)])
});

export const subscribeRequestSchema = z.object({
    event: z.string(),
    name: z.string()
});

export const subscribeResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const unsubscribeRequestSchema = z.object({
    event: z.string(),
    name: z.string()
});

export const unsubscribeResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const publishRequestSchema = z.object({
    event: z.string(),
    data: nullableJsonRecordSchema.optional(),
    options: sendOptionsSchema.optional()
});

export const publishResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const cancelRequestSchema = z.object({
    name: z.string(),
    id: z.union([z.string(), z.array(z.string())]),
    options: connectionOptionsSchema.optional()
});

export const cancelResponseSchema = z.object({
    ok: z.literal(true),
    result: commandResponseSchema
});

export const resumeRequestSchema = z.object({
    name: z.string(),
    id: z.union([z.string(), z.array(z.string())]),
    options: connectionOptionsSchema.optional()
});

export const resumeResponseSchema = z.object({
    ok: z.literal(true),
    result: commandResponseSchema
});

export const retryRequestSchema = z.object({
    name: z.string(),
    id: z.union([z.string(), z.array(z.string())]),
    options: connectionOptionsSchema.optional()
});

export const retryResponseSchema = z.object({
    ok: z.literal(true),
    result: commandResponseSchema
});

export const deleteJobRequestSchema = z.object({
    name: z.string(),
    id: z.union([z.string(), z.array(z.string())]),
    options: connectionOptionsSchema.optional()
});

export const deleteJobResponseSchema = z.object({
    ok: z.literal(true),
    result: commandResponseSchema
});

export const deleteQueuedJobsRequestSchema = z.object({
    name: z.string()
});

export const deleteQueuedJobsResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const deleteStoredJobsRequestSchema = z.object({
    name: z.string()
});

export const deleteStoredJobsResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const deleteAllJobsRequestSchema = z.object({
    name: z.string().optional()
});

export const deleteAllJobsResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const completeOptionsSchema = connectionOptionsSchema.and(z.object({
    includeQueued: z.boolean().optional()
}));

export const completeRequestSchema = z.object({
    name: z.string(),
    id: z.union([z.string(), z.array(z.string())]),
    data: nullableJsonRecordSchema.optional(),
    options: completeOptionsSchema.optional()
});

export const completeResponseSchema = z.object({
    ok: z.literal(true),
    result: commandResponseSchema
});

export const failRequestSchema = z.object({
    name: z.string(),
    id: z.union([z.string(), z.array(z.string())]),
    data: nullableJsonRecordSchema.optional(),
    options: connectionOptionsSchema.optional()
});

export const failResponseSchema = z.object({
    ok: z.literal(true),
    result: commandResponseSchema
});

export const findJobsRequestSchema = z.object({
    name: z.string(),
    options: findJobsOptionsSchema.optional()
});

export const findJobsResponseSchema = z.object({
    ok: z.literal(true),
    result: z.array(jobWithMetadataSchema)
});

export const createQueueRequestSchema = z.object({
    name: z.string(),
    options: queueOptionsSchema.and(z.object({
        policy: z.string().optional(),
        partition: z.boolean().optional(),
        deadLetter: z.string().optional(),
        warningQueueSize: z.number().optional()
    })).optional()
});

export const createQueueResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const getBlockedKeysRequestSchema = z.object({
    name: z.string()
});

export const getBlockedKeysResponseSchema = z.object({
    ok: z.literal(true),
    result: z.array(z.string())
});

export const updateQueueRequestSchema = z.object({
    name: z.string(),
    options: updateQueueOptionsSchema.optional()
});

export const updateQueueResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const deleteQueueRequestSchema = z.object({
    name: z.string()
});

export const deleteQueueResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const getQueuesRequestSchema = z.object({
    names: z.array(z.string()).optional()
});

export const getQueuesResponseSchema = z.object({
    ok: z.literal(true),
    result: z.array(queueResultSchema)
});

export const getQueueRequestSchema = z.object({
    name: z.string()
});

export const getQueueResponseSchema = z.object({
    ok: z.literal(true),
    result: queueResultSchema.nullable()
});

export const getQueueStatsRequestSchema = z.object({
    name: z.string()
});

export const getQueueStatsResponseSchema = z.object({
    ok: z.literal(true),
    result: queueResultSchema
});

export const superviseRequestSchema = z.object({
    name: z.string().optional()
});

export const superviseResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const isInstalledResponseSchema = z.object({
    ok: z.literal(true),
    result: z.boolean()
});

export const schemaVersionResponseSchema = z.object({
    ok: z.literal(true),
    result: z.number().nullable()
});

export const scheduleRequestSchema = z.object({
    name: z.string(),
    cron: z.string(),
    data: nullableJsonRecordSchema.optional(),
    options: scheduleOptionsSchema.optional()
});

export const scheduleResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const unscheduleRequestSchema = z.object({
    name: z.string(),
    key: z.string().optional()
});

export const unscheduleResponseSchema = z.object({
    ok: z.literal(true),
    result: z.null()
});

export const getSchedulesRequestSchema = z.object({
    name: z.string().optional(),
    key: z.string().optional()
});

export const getSchedulesResponseSchema = z.object({
    ok: z.literal(true),
    result: z.array(scheduleSchema)
});

export const getBamStatusResponseSchema = z.object({
    ok: z.literal(true),
    result: z.array(bamStatusSummarySchema)
});

export const insertRequestSchema = z.object({
    name: z.string(),
    jobs: z.array(jobInsertSchema),
    options: insertOptionsSchema.optional()
});
