// Generates src/schema.json: the canonical, catalog-introspected shape of a freshly created
// pg-boss schema, for both the partitioned and non-partitioned architectures. The drift check compares
// the live database against this manifest, so the CREATE TABLE/FUNCTION/INDEX DDL in plans.ts is the
// single source of truth — the manifest is a generated artifact, never hand-edited.
//
// It runs entirely in-process on pglite (a WASM Postgres), so no external database is needed. The same
// drifter.getSchema* introspection queries the runtime drift check uses are reused here, which keeps
// the manifest and the live scan structurally identical by construction.
//
// Regenerate with `npm run gen:manifest`. CI verifies it is up to date via `git diff --exit-code`, so a
// DDL change that forgets to regenerate is a red build rather than silent drift.

import { PGlite } from '@electric-sql/pglite'
import { writeFileSync, readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as plans from '../src/plans.ts'
import * as drifter from '../src/drifter.ts'
import packageJson from '../package.json' with { type: 'json' }

// A distinctive schema name so templating it back out to a placeholder can't collide with anything the
// catalog legitimately emits (type names, column literals, etc.).
const GEN_SCHEMA = '__pgboss_manifest__'
const SCHEMA_TOKEN = '{{schema}}'
const version = packageJson.pgboss.schema as number

const q = async (pg: PGlite, sql: string): Promise<any[]> => (await pg.query(sql)).rows

// Replaces the throwaway generation schema name with a placeholder everywhere it appears in
// catalog-emitted text (pg_get_constraintdef / pg_get_indexdef / pg_get_functiondef embed it, as do
// enum-typed column types and defaults), so the manifest is schema-name agnostic.
function templateSchema<T> (value: T): T {
  return JSON.parse(JSON.stringify(value).split(GEN_SCHEMA).join(SCHEMA_TOKEN))
}

// The queue_stats range partitions are provisioned per calendar day (queue_stats_YYYYMMDD), so their
// names are non-deterministic and must not enter the manifest — same treatment the drift check gives
// dynamic per-queue job partitions. They inherit the parent's shape, so nothing is lost.
const isDynamicPartition = (table: string) => /^queue_stats_\d+$/.test(table)

async function introspect (pg: PGlite) {
  const drop = <T extends { table: string }>(rows: T[]) => rows.filter(r => !isDynamicPartition(r.table))
  const columns = drop(await q(pg, drifter.getSchemaColumns(GEN_SCHEMA)))
  const constraints = drop(await q(pg, drifter.getSchemaConstraints(GEN_SCHEMA)))
  // Only the standalone managed indexes are expectations; constraint-backing indexes (*_pkey) are
  // covered by the constraint check, and their `constraintBacked` flag is dropped from the stored rows.
  const indexes = drop(await q(pg, drifter.getSchemaIndexes(GEN_SCHEMA)))
    .filter(r => !r.constraintBacked)
    .map(({ name, table, valid, def }) => ({ name, table, valid, def }))
  const functions = await q(pg, drifter.getSchemaFunctions(GEN_SCHEMA))
  const enumLabels = (await q(pg, drifter.getEnumDefinition(GEN_SCHEMA))).map(r => r.label as string)
  const tables = [...new Set(columns.map(c => c.table as string))]

  // Sort everything to a stable order so regeneration produces a deterministic, diff-friendly file.
  // The enum is left in catalog (enumsortorder) order — its ordering is semantically significant.
  const byTableCol = (a: any, b: any) => (a.table + a.column).localeCompare(b.table + b.column)
  const byTableDef = (a: any, b: any) => (a.table + a.def).localeCompare(b.table + b.def)

  return templateSchema({
    tables: tables.sort(),
    columns: columns.sort(byTableCol),
    constraints: constraints.sort(byTableDef),
    indexes: indexes.slice().sort((a, b) => (a.table + a.name).localeCompare(b.table + b.name)),
    functions: functions.slice().sort((a, b) => (a.name as string).localeCompare(b.name)),
    enum: enumLabels
  })
}

async function buildFor (partitioned: boolean) {
  const pg = new PGlite()
  try {
    // noAdvisoryLocks: pglite is single-connection, so the advisory lock is unnecessary and pglite does
    // not honor it anyway. noTablePartitioning selects the architecture.
    const sql = plans.create(GEN_SCHEMA, version, {
      createSchema: true,
      noAdvisoryLocks: true,
      noTablePartitioning: !partitioned
    })
    await pg.exec(sql)
    return await introspect(pg)
  } finally {
    await pg.close()
  }
}

const manifest = {
  // A note for anyone who opens the generated file.
  _generated: 'Generated by scripts/gen-manifest.ts — do not edit by hand. Run `npm run gen:manifest`.',
  version,
  schemaToken: SCHEMA_TOKEN,
  partitioned: await buildFor(true),
  nonPartitioned: await buildFor(false)
}

const outPath = resolve(dirname(fileURLToPath(import.meta.url)), '../src/schema.json')
const serialized = JSON.stringify(manifest, null, 2) + '\n'

// `--check` (used by CI / pretest) verifies the committed manifest matches what the current DDL would
// produce, without touching the file or needing a git working tree. A mismatch means someone changed
// the schema DDL without regenerating — fail with a clear instruction.
if (process.argv.includes('--check')) {
  let existing: string | null = null
  try {
    existing = readFileSync(outPath, 'utf8')
  } catch {
    existing = null
  }
  if (existing !== serialized) {
    console.error(`${outPath} is out of date. Run \`npm run gen:manifest\` and commit the result.`)
    process.exit(1)
  }
  console.log(`schema manifest is up to date (schema v${version})`)
} else {
  writeFileSync(outPath, serialized)
  console.log(`wrote ${outPath} (schema v${version})`)
}
